# Final Project
library(ggplot2)
library(dplyr)
library(shiny)
library(tidyverse)
library(DT)
library(plotly)

setwd <- ("~/Desktop/final")
m_data <- read.csv("movie_metadata.csv") %>% as.data.frame()
  
my.server <- function(input, output) {
  output$data_info <- renderText({
    paste("Data generated from the IMDB dataset")
  })
  output$info <- renderText({
    paste("This application generates movie recommendations based on the user's input.
          The user will be asked to select its preferred genre of the movie, country where the movie is filmed,
          content rating of the movie, as well as the IMDB rating of the movie. After selecting those preferences,
          this application will filter out movies that match the user's preference. The table below shows the title 
          of the movie, the plot keywords of the movie, the duration of the movie, and lastly, the rating of the movie.")
  })
  output$graph_info <- renderText({
    paste("Based on the plots, our group found that based on the IMDB score, there is an increasing trend curve
          that corresponds to the number of Facebook likes and the revenue generated by the movie.
          For example, based on a low IMDB score, that movie should correspond to a low amount of likes which 
          also means a lower gross revenue. The number of likes on Facebook is a good indicator of
          the gross revenue generated by the movie. ")
  })
  filter_data <- reactive({

    data <- m_data %>% filter(title_year ==input$year) %>% 
      filter(imdb_score <=input$i_rating[2]) %>% 
      filter (imdb_score >= input$i_rating[1]) %>% 
      filter(str_detect(genres, input$genre)) %>% 
      filter(content_rating == input$c_rating) %>% 
      filter(country == input$country)
    num <- nrow(data)
    if (num > 10) {
      num <- 10
    }
    data <- sample_n(data, num)
  })
  output$table <- DT::renderDT({
    datatable((select(filter_data(), "movie_title", "plot_keywords", "duration", "imdb_score")), options = list(paging = FALSE), rownames = FALSE)
  })
  output$plot1 <- renderPlotly({
    plot_data <- filter(filter_data())
    ggplot(plot_data, aes(x = imdb_score, y = movie_facebook_likes)) +
      labs(y = "Number of Likes on Facebook", x = "IMDB Score") +
      geom_point(aes(label=movie_title)) +
      ggtitle("Likes vs Rating Chart ") + 
      theme(plot.title = element_text(face="bold", size=20, color = "lightpink2")) +
      theme(axis.title = element_text(face="bold", size=15, color = "dodgerblue3")) +
      theme(panel.background = element_rect(fill = "grey87", colour = "grey87", size = 0.5, linetype = "solid")) +
      theme(panel.grid.major.y = element_line(size = 1, colour = "lavenderblush2")) + 
      theme(panel.grid.major = element_line(size = 1, colour = "lavenderblush2"))
  })
  output$plot2 <- renderPlotly({
    plot_data <- filter(filter_data())
    ggplot(plot_data, aes(x = imdb_score, y = gross)) +
      labs(y = "Revenue Generated by a Movie", x = "IMDB score of a Movie") +
      geom_point(aes(label=movie_title)) +
      ggtitle("Gross vs Rating Chart") + 
      theme(plot.title = element_text(face="bold", size=20, color = "lightpink2")) +
      theme(axis.title = element_text(face="bold", size=15, color = "dodgerblue3")) +
      theme(panel.background = element_rect(fill = "grey87",colour = "grey87", size = 0.5, linetype = "solid")) +
      theme(panel.grid.major.y = element_line(size = 1, colour = "lavenderblush2")) + 
      theme(panel.grid.major = element_line(size = 1, colour = "lavenderblush2"))
  })
  output$plot3 <- renderPlotly({
    plot_data <- filter(filter_data())
    ggplot(plot_data, aes(x = movie_facebook_likes, y = gross)) +
      labs(y = "Revenue Generated by a Movie", x = "Number of Likes on Facebook") +
      geom_point(aes(label=movie_title))+
      ggtitle("Gross vs Likes Chart") + 
      theme(plot.title = element_text(face="bold", size=20, color = "lightpink2")) +
      theme(axis.title = element_text(face="bold", size=15, color = "dodgerblue3")) +
      theme(panel.background = element_rect(fill = "grey87",colour = "grey87",  size = 0.5, linetype = "solid")) +
      theme(panel.grid.major.y = element_line(size = 1, colour = "lavenderblush2")) + 
      theme(panel.grid.major = element_line(size = 1, colour = "lavenderblush2"))
  })
}
shinyServer(my.server)